// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: schema.proto
#ifndef GRPC_schema_2eproto__INCLUDED
#define GRPC_schema_2eproto__INCLUDED

#include "schema.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace NfsProtocol {

class NfsServer final {
 public:
  static constexpr char const* service_full_name() {
    return "NfsProtocol.NfsServer";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status mkdir(::grpc::ClientContext* context, const ::NfsProtocol::mkdir_request& request, ::NfsProtocol::mkdir_response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NfsProtocol::mkdir_response>> Asyncmkdir(::grpc::ClientContext* context, const ::NfsProtocol::mkdir_request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NfsProtocol::mkdir_response>>(AsyncmkdirRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NfsProtocol::mkdir_response>> PrepareAsyncmkdir(::grpc::ClientContext* context, const ::NfsProtocol::mkdir_request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NfsProtocol::mkdir_response>>(PrepareAsyncmkdirRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void mkdir(::grpc::ClientContext* context, const ::NfsProtocol::mkdir_request* request, ::NfsProtocol::mkdir_response* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::NfsProtocol::mkdir_response>* AsyncmkdirRaw(::grpc::ClientContext* context, const ::NfsProtocol::mkdir_request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::NfsProtocol::mkdir_response>* PrepareAsyncmkdirRaw(::grpc::ClientContext* context, const ::NfsProtocol::mkdir_request& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status mkdir(::grpc::ClientContext* context, const ::NfsProtocol::mkdir_request& request, ::NfsProtocol::mkdir_response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NfsProtocol::mkdir_response>> Asyncmkdir(::grpc::ClientContext* context, const ::NfsProtocol::mkdir_request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NfsProtocol::mkdir_response>>(AsyncmkdirRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NfsProtocol::mkdir_response>> PrepareAsyncmkdir(::grpc::ClientContext* context, const ::NfsProtocol::mkdir_request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NfsProtocol::mkdir_response>>(PrepareAsyncmkdirRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void mkdir(::grpc::ClientContext* context, const ::NfsProtocol::mkdir_request* request, ::NfsProtocol::mkdir_response* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::NfsProtocol::mkdir_response>* AsyncmkdirRaw(::grpc::ClientContext* context, const ::NfsProtocol::mkdir_request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::NfsProtocol::mkdir_response>* PrepareAsyncmkdirRaw(::grpc::ClientContext* context, const ::NfsProtocol::mkdir_request& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_mkdir_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status mkdir(::grpc::ServerContext* context, const ::NfsProtocol::mkdir_request* request, ::NfsProtocol::mkdir_response* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_mkdir : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_mkdir() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_mkdir() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status mkdir(::grpc::ServerContext* context, const ::NfsProtocol::mkdir_request* request, ::NfsProtocol::mkdir_response* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestmkdir(::grpc::ServerContext* context, ::NfsProtocol::mkdir_request* request, ::grpc::ServerAsyncResponseWriter< ::NfsProtocol::mkdir_response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_mkdir<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_mkdir : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_mkdir() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::NfsProtocol::mkdir_request, ::NfsProtocol::mkdir_response>(
          [this](::grpc::ServerContext* context,
                 const ::NfsProtocol::mkdir_request* request,
                 ::NfsProtocol::mkdir_response* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->mkdir(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_mkdir() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status mkdir(::grpc::ServerContext* context, const ::NfsProtocol::mkdir_request* request, ::NfsProtocol::mkdir_response* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void mkdir(::grpc::ServerContext* context, const ::NfsProtocol::mkdir_request* request, ::NfsProtocol::mkdir_response* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_mkdir<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_mkdir : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_mkdir() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_mkdir() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status mkdir(::grpc::ServerContext* context, const ::NfsProtocol::mkdir_request* request, ::NfsProtocol::mkdir_response* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_mkdir : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_mkdir() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_mkdir() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status mkdir(::grpc::ServerContext* context, const ::NfsProtocol::mkdir_request* request, ::NfsProtocol::mkdir_response* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestmkdir(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_mkdir : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_mkdir() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->mkdir(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_mkdir() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status mkdir(::grpc::ServerContext* context, const ::NfsProtocol::mkdir_request* request, ::NfsProtocol::mkdir_response* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void mkdir(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_mkdir : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_mkdir() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::NfsProtocol::mkdir_request, ::NfsProtocol::mkdir_response>(std::bind(&WithStreamedUnaryMethod_mkdir<BaseClass>::Streamedmkdir, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_mkdir() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status mkdir(::grpc::ServerContext* context, const ::NfsProtocol::mkdir_request* request, ::NfsProtocol::mkdir_response* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedmkdir(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::NfsProtocol::mkdir_request,::NfsProtocol::mkdir_response>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_mkdir<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_mkdir<Service > StreamedService;
};

}  // namespace NfsProtocol


#endif  // GRPC_schema_2eproto__INCLUDED
