// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: schema.proto

#include "schema.pb.h"
#include "schema.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace NfsProtocol {

static const char* NfsServer_method_names[] = {
  "/NfsProtocol.NfsServer/mkdir",
};

std::unique_ptr< NfsServer::Stub> NfsServer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< NfsServer::Stub> stub(new NfsServer::Stub(channel));
  return stub;
}

NfsServer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_mkdir_(NfsServer_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status NfsServer::Stub::mkdir(::grpc::ClientContext* context, const ::NfsProtocol::mkdir_request& request, ::NfsProtocol::mkdir_response* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_mkdir_, context, request, response);
}

void NfsServer::Stub::experimental_async::mkdir(::grpc::ClientContext* context, const ::NfsProtocol::mkdir_request* request, ::NfsProtocol::mkdir_response* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_mkdir_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::NfsProtocol::mkdir_response>* NfsServer::Stub::AsyncmkdirRaw(::grpc::ClientContext* context, const ::NfsProtocol::mkdir_request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::NfsProtocol::mkdir_response>::Create(channel_.get(), cq, rpcmethod_mkdir_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::NfsProtocol::mkdir_response>* NfsServer::Stub::PrepareAsyncmkdirRaw(::grpc::ClientContext* context, const ::NfsProtocol::mkdir_request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::NfsProtocol::mkdir_response>::Create(channel_.get(), cq, rpcmethod_mkdir_, context, request, false);
}

NfsServer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NfsServer_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NfsServer::Service, ::NfsProtocol::mkdir_request, ::NfsProtocol::mkdir_response>(
          std::mem_fn(&NfsServer::Service::mkdir), this)));
}

NfsServer::Service::~Service() {
}

::grpc::Status NfsServer::Service::mkdir(::grpc::ServerContext* context, const ::NfsProtocol::mkdir_request* request, ::NfsProtocol::mkdir_response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace NfsProtocol

